version: '3.4'

services:
  authservice:
    image: authservice
    build:
      context: team-service
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 7080:7080
