version: '3.4'

services:
  authservice:
    image: authservice
    build:
      context: team-service
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 7080:7080
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
